services:
  postgres:
    image: postgres:17.2-alpine3.21
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=warehouse
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}
